SELECT * FROM EMP
WHERE JOB IN ('CLERK','MANAGER');

SELECT GETDATE()

SELECT * FROM EMP
WHERE SAL BETWEEN 500 AND 1000

SELECT * FROM EMP
WHERE MONTH(HIREDATE) = '12'

SELECT * FROM EMP
WHERE SAL NOT BETWEEN 1000 AND 2500

SELECT * FROM EMP
WHERE SAL IN ('800','950','3000','5000');

SELECT * FROM EMP
WHERE ENAME LIKE '_L%'

SELECT * FROM EMP
WHERE ENAME LIKE '%D'

SELECT * FROM EMP
WHERE LEN(ENAME) = 5

SELECT * FROM EMP
WHERE ENAME LIKE 'T%R'

SELECT * FROM EMP
WHERE ENAME LIKE 'A%'

SELECT EMPNO,ENAME FROM EMP
WHERE ENAME = 'JAMES'

SELECT SAL,ENAME FROM EMP
WHERE ENAME = 'KING'

SELECT * FROM EMP
WHERE JOB = 'PRESIDENT'

SELECT * FROM EMP
WHERE JOB = 'MANAGER'

SELECT * FROM EMP
WHERE COMM IS NOT NULL

SELECT * FROM EMP
WHERE HIREDATE < '1981-04-01'

SELECT SAL,ENAME FROM EMP
WHERE ENAME IN ('KING','BLAKE','FORD','SMITH');

SELECT * FROM EMP
WHERE SAL < '3500'

SELECT SAL*12,ENAME
FROM EMP

SELECT SUM(SAL),DEPTNO
FROM EMP
GROUP BY DEPTNO

SELECT ((SAL*120)/100)*12
FROM EMP
WHERE ENAME = 'FORD'

SELECT ENAME,SAL FROM EMP WHERE SAL =(
SELECT MIN(SAL) FROM EMP
GROUP BY DEPTNO
HAVING DEPTNO = '10');

SELECT SAL,ENAME FROM EMP
WHERE JOB ='MANAGER'

SELECT SUM(SAL)FROM EMP
WHERE JOB = 'SALESMAN'

SELECT COUNT(*),JOB FROM EMP
GROUP BY (JOB)

SELECT MAX(SAL) FROM EMP
WHERE JOB = 'ANALYST'

SELECT MAX(COMM) FROM EMP

SELECT COUNT(DISTINCT DEPTNO) FROM EMP

SELECT * FROM EMP
WHERE ENAME LIKE '__L%'

SELECT DEPTNO FROM DEPT EXCEPT SELECT DISTINCT DEPTNO FROM EMP 

SELECT ENAME,JOB FROM EMP
WHERE MGR IS NULL

SELECT * FROM EMP
SELECT * FROM DEPT

SELECT * 
FROM EMP
LEFT JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO

 
