SELECT Manager_Name FROM PMS_MANAGER_DETAILS
WHERE Commission = '0'

SELECT Manager_Name, Salary FROM PMS_MANAGER_DETAILS WHERE Salary =
(SELECT DISTINCT MAX(Salary) AS HIGH_SALARY FROM PMS_MANAGER_DETAILS
WHERE JOB = 'ASSISTANT MANAGER'
GROUP BY Job );

SELECT DEPARTMENT_EXTENSION FROM PMS_DEPARTMENT_DETAILS
WHERE DEPARTMENT_NAME = 'CUSTOMER CARE SECTION'

SELECT PRODUCT_NAME, QUANTITY FROM PMS_MANUFACTURING
LEFT JOIN  PMS_PRODUCT
ON PMS_PRODUCT.PRODUCT_ID = PMS_MANUFACTURING.PRODUCT_ID
WHERE QUANTITY > '1000' AND AVAILABILITY = 'YES'

SELECT PRODUCT_NAME FROM PMS_PRODUCT 
LEFT JOIN PMS_DEPARTMENT_DETAILS
ON PMS_PRODUCT.DEPARTMENT_ID = PMS_DEPARTMENT_DETAILS.DEPARTMENT_ID
WHERE DEPARTMENT_NAME = 'BI_PRODUCTS SECTION'

SELECT Manager_Name FROM PMS_MANAGER_DETAILS
LEFT JOIN PMS_DEPARTMENT_DETAILS
ON PMS_MANAGER_DETAILS.DEPARTMENT_ID = PMS_DEPARTMENT_DETAILS.DEPARTMENT_ID
WHERE DEPARTMENT_NAME = 'DISPATCH SECTION' AND JOB = 'MANAGER'

SELECT PRODUCT_ID,UNIT_ID,YEAR(PRODUCT_MANFACTURE_DATE) M_Year,MONTH(PRODUCT_MANFACTURE_DATE) M_Month
FROM PMS_MANUFACTURING


SELECT 'DEPARTMENT '+ CAST(DEPARTMENT_ID AS VARCHAR) DEPARTMENT_NUMBER
FROM PMS_DEPARTMENT_DETAILS

SELECT  MANFATURE_ID, PRODUCT_NAME, UNIT_ID, QUANTITY, PRODUCT_MANFACTURE_DATE,PRODUCT_EXPIRY_DATE
FROM PMS_MANUFACTURING 
LEFT JOIN PMS_PRODUCT
ON PMS_MANUFACTURING.PRODUCT_ID = PMS_PRODUCT.PRODUCT_ID
 LEFT JOIN PMS_DEPARTMENT_DETAILS
ON PMS_DEPARTMENT_DETAILS.DEPARTMENT_ID = PMS_PRODUCT.DEPARTMENT_ID
WHERE DEPARTMENT_NAME = 'GHEE SECTION';
 
SELECT DEPARTMENT_ID,DEPARTMENT_NAME FROM PMS_DEPARTMENT_DETAILS WHERE DEPARTMENT_ID =
(SELECT DEPARTMENT_ID FROM PMS_DEPARTMENT_DETAILS EXCEPT SELECT DEPARTMENT_ID FROM PMS_MANAGER_DETAILS);

SELECT M1.Manager_ID, M1.Manager_Name,M1.Job,M2.Manager_Name FROM PMS_MANAGER_DETAILS M1
LEFT JOIN PMS_MANAGER_DETAILS M2
ON M1.Boss_Code = M2.Manager_ID


SELECT PRODUCT_ID,LOWER(PRODUCT_NAME) PRODUCT_NAME,DEPARTMENT_ID FROM PMS_PRODUCT
WHERE PRODUCT_ID IN(SELECT PRODUCT_ID FROM PMS_PRODUCT_UNIT WHERE UNIT_ID=(SELECT UNIT_ID FROM PMS_UNIT_DETAILS
WHERE UNIT_NAME='HALF_PACK'));

SELECT PRODUCT_NAME FROM PMS_PRODUCT 
WHERE PRODUCT_ID=(SELECT PRODUCT_ID FROM PMS_PRODUCT_UNIT
WHERE UNIT_ID=(SELECT UNIT_ID FROM PMS_UNIT_DETAILS WHERE UNIT_NAME='CAN'))

SELECT DEPARTMENT_ID FROM(
SELECT TOP 1 P.DEPARTMENT_ID,SUM(M.QUANTITY) TOTAL
FROM PMS_PRODUCT P,PMS_MANUFACTURING M
WHERE M.PRODUCT_ID=P.PRODUCT_ID
GROUP BY P.DEPARTMENT_ID
ORDER BY TOTAL DESC) DUP;
