SELECT PIECE_WEIGHT FROM PMS_UNIT_DETAILS
WHERE UNIT_NAME = 'CHOTA_PACK'

SELECT Manager_Name,Manager_ID FROM PMS_MANAGER_DETAILS
WHERE  Boss_Code = (SELECT Manager_ID FROM PMS_MANAGER_DETAILS WHERE Manager_Name = 'LARANCE');

SELECT Manager_Name FROM PMS_MANAGER_DETAILS WHERE Manager_ID = (SELECT Boss_Code FROM PMS_MANAGER_DETAILS 
WHERE Manager_Name = 'GOUD');

SELECT DEPARTMENT_LOCATION FROM PMS_DEPARTMENT_DETAILS
WHERE DEPARTMENT_NAME = 'GHEE SECTION'

SELECT DEPARTMENT_NAME FROM PMS_DEPARTMENT_DETAILS
WHERE DEPARTMENT_LOCATION LIKE 'HYDERABAD%'

SELECT DEPARTMENT_ID FROM PMS_PRODUCT
WHERE PRODUCT_NAME = 'DOODH PEDA'

SELECT PRODUCT_NAME FROM PMS_PRODUCT
WHERE PRODUCT_NAME != 'RASAGULLA' AND DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM PMS_PRODUCT WHERE PRODUCT_NAME = 'RASAGULLA');

SELECT DISTINCT PRODUCT_MANFACTURE_DATE, PRODUCT_EXPIRY_DATE, PRODUCT_NAME FROM PMS_MANUFACTURING
LEFT JOIN PMS_PRODUCT
ON PMS_MANUFACTURING.PRODUCT_ID  = PMS_PRODUCT.PRODUCT_ID 

SELECT COUNT(*) FROM PMS_MANAGER_DETAILS
WHERE JOB = 'MANAGER'

SELECT Commission + salary as bonus_salary,Manager_Name FROM PMS_MANAGER_DETAILS

